const CMD_TO_FIELD = {
  "ULTIMO CIERRE": "ULTIMO_CIERRE",
  "ULTIMO VENCIMIENTO": "ULTIMO_VENCIMIENTO",
  "PROXIMO CIERRE": "PROXIMO_CIERRE",
  "PROXIMO VENCIMIENTO": "PROXIMO_VENCIMIENTO"
};

const TARJETA_FIELD_TO_OFFSET = {
  'ULTIMO_CIERRE': 1,
  'ULTIMO_VENCIMIENTO': 2,
  'PROXIMO_CIERRE': 3,
  'PROXIMO_VENCIMIENTO': 4
};