const MSG_ERRORS = {
  FECHA_INVALIDA: "📅 Fecha inválida. Usá formato DD/MM o - si querés la fecha actual",
  FECHA_INVALIDA_STRICT: "📅 Fecha inválida. Usá DD/MM.",
  ERROR_GENERIC: "No se porqué pero pasó esto, avisale a Pablo: ",
  ERRORES_PREFIX: "⚠️ Te mandaste las siguientes macanas:\n\n",
  MONTO_INVALIDO: "💵 Monto inválido. Debe ser un número (ej: 1200.50)",
  MONEDA_INVALIDA: "💱 Moneda inválida. Solo USD, USDT o ARS.",
  METODO_INVALIDO: "💳 El medio de pago no puede estar vacío.",
  AHORRO_INVALIDO: "💾 Ahorro inválido. Indicá un número positivo o un porcentaje (ej: 15 o 15%).",
  PORCENTAJE_INVALIDO: "💾 El porcentaje de ahorro debe ser un número positivo (ej: 10%).",
  MONTO_BASE_INVALIDO: "💵 Monto base inválido para calcular porcentaje.",
  VALOR_REINTEGRO_INVALIDO: "↩️ Valor inválido en reintegrado. Solo se acepta 'si' o 'no'.",
  CUOTAS_INVALIDO: "🧮 #Cuotas inválido. Debe ser un entero positivo (ej: 12)",
  DETALLE_VACIO: "📌 Descripción no puede estar vacía.",
  NUMERO_INVALIDO: "❌ Número inválido. Elegí un número de la lista o creá una NUEVA.",
  FORMATO_INCORRECTO_NUEVA: "Tenés que poner un nombre después de NUEVA",
  INVALID_COMMAND: "Elegí un comando válido. Podés ver la lista con COMANDOS",
  INVALID_MONTH: "Mes inválido. Usá un número entre 1-12 o el nombre completo del mes.",
  TIPO_INVALIDO: "Tipo inválido. Usá D para descuento, R para reintegro o - si no aplica ninguno.",
  REFUND_INPUT_INVALIDO_1: "Si el tipo es '-', el ahorro debería ser 0.",
  REFUND_INPUT_INVALIDO_2: "Si el tipo es '-', el campo Reintegrado debe ser '-'.",
  REFUND_INPUT_INVALIDO_3: "Si el tipo es 'D', el campo Reintegrado debe ser '-' o 'Sí'.",
  REFUND_INPUT_INVALIDO_4: "Si el tipo es 'R', el ahorro/reintegro debe ser mayor a 0.",
  REFUND_INPUT_INVALIDO_5: "Si el tipo es 'R', Reintegrado debe ser 'Sí' o 'No'."
};